
(* AM: mostly autogenerated mli *)

module TOML :
  sig
    val from_filename : string -> Toml.Types.table
    val from_filename' : string -> Toml.Parser.result
    val force : 'a option -> 'a
    val has : string -> Toml.Types.table -> bool
    val get_string : string -> Toml.Types.table -> string
    val get_string' : string -> Toml.Types.table -> string option
    val get_nonempty_string' : string -> Toml.Types.table -> string option
    val get_default_string : string -> string -> Toml.Types.table -> string
    val get_int : string -> Toml.Types.table -> int
    val get_int' : string -> Toml.Types.table -> int option
    val get_default_int : int -> string -> Toml.Types.table -> int
    val get_float : string -> Toml.Types.table -> float
    val get_bool : string -> Toml.Types.table -> bool
    val get_bool_array : string -> Toml.Types.table -> bool list
    val get_table : string -> Toml.Types.table -> Toml.Types.table
    val get_table_array : string -> Toml.Types.table -> Toml.Types.table list
    val get_table_array' :
      string -> Toml.Types.table -> Toml.Types.table list option
    val iter_over :
      string -> Toml.Types.table -> f:(Toml.Types.table -> unit) -> unit
  end
