title = "Class Gifts"

[[examples]]
description = "Gift to spouse"
program = """
A and B marry.
To the spouse of A.
"""
result = "Fee simple in B."


[[examples]]
description = "Gift to spouse via will"
program = """
A and B marry.
O makes a will to the spouse of A.
A and B divorce.
A and C marry.
O dies.
"""
result = "Fee simple in C."


[[examples]]
description = "Gift to surviving spouse"
program = """
A and B marry.
A dies.
To the widower of A.
"""
result = "Fee simple in B."


[[examples]]
description = "Gift to children"
program = """
A has child B.
A has child C.
A has child D.
To the children of A.
"""
result = "Tenancy in common, B: 1/3, C: 1/3, D: 1/3"


[[examples]]
description = "Gift to grandchildren"
program = """
A has child B.
A has child C.
A has child D.
B has child P.
C has child Q.
C has child R.
To the grandchildren of A.
"""
result = "Tenancy in common, P: 1/3, Q: 1/3, R: 1/3"


[[examples]]
description = "Gift to empty class"
program = """
To the children of A.
"""
result = "Fee simple in O."